service:
  name: livescan2

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: default
  region: eu-west-1
  environment:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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

functions:
  healthCheck:
    handler: src/healthCheck.default
    events:
      - http:
          method: get
          path: healthCheck
