service:
  name: livescan2

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: default
  region: eu-west-1

functions:
  healthCheck:
    handler: src/healthCheck.default
    events:
      - http:
          method: get
          path: healthCheck
